### ISSUE TITLE
No compatible with NativeAOT.

### ISSUE THREAD

**Issue by Nab0y** [openai/openai-dotnet#243]
### Service

OpenAI

### Describe the bug

Starting from version OpenAI_2.0.0-beta.8, the library is no longer compatible with NativeAOT.

### Steps to reproduce

1. Create sample console application
2. Insert example code from Example01_SimpleChat.cs
3. Enable Native Compilation in project settings.
```
<PropertyGroup>
        <OutputType>Exe</OutputType>
       ...
        <PublishAot>true</PublishAot>
       ...
</PropertyGroup>
``` 
4. Launch project, get error

> System.InvalidOperationException: Reflection-based serialization has been disabled for this application. Either use the source generator APIs or explicitly configure the 'JsonSerializerOptions.TypeInfoResolver' property.
   at System.Text.Json.ThrowHelper.ThrowInvalidOperationException_JsonSerializerIsReflectionDisabled()
   at System.Text.Json.JsonSerializerOptions.ConfigureForJsonSerializer()
   at System.Text.Json.JsonSerializer.GetTypeInfo(JsonSerializerOptions options, Type inputType)
   at System.Text.Json.JsonSerializer.SerializeToUtf8Bytes(Object value, Type inputType, JsonSerializerOptions options)
   at System.BinaryData.FromObjectAsJson[T](T jsonSerializable, JsonSerializerOptions options)
   at OpenAI.ModelSerializationExtensions..cctor() in /home/nab0y/Projects/openai-dotnet/src/Generated/Internal/ModelSerializationExtensions.cs:line 18

### OS

linux, win, macOs

### .NET version

8.0

### Library version

Starting from version OpenAI_2.0.0-beta.8,

**Comment by joseharriaga** [comment]
Thank you for reaching out, @Nab0y ! This is fixed as of version 2.2.0-beta.1.
